// vue-version/src/components/Header.vue
<script setup>
import { ref, computed } from 'vue'
import { RouterLink, useRouter } from 'vue-router'

const router = useRouter() // For programmatic navigation
const isLoggedIn = computed(() => !!localStorage.getItem('ticketapp_session'))
const isMobileMenuOpen = ref(false) // Mobile menu state

// Logout: remove token, redirect to landing
const handleLogout = () => {
  localStorage.removeItem('ticketapp_session')
  router.push('/')
}

// Toggle mobile menu
const toggleMobileMenu = () => {
  isMobileMenuOpen.value = !isMobileMenuOpen.value
}

// Close menu when a link inside mobile nav is clicked
const handleMobileLinkClick = () => {
  isMobileMenuOpen.value = false
}

// Handle logout + close menu on mobile
const handleMobileLogoutClick = () => {
  handleLogout()
  isMobileMenuOpen.value = false
}
</script>

<template>
  <header class="main-header">
    <nav class="container">
      <RouterLink to="/" class="logo">SOLPOINT</RouterLink>

      <button
        :class="['mobile-nav-toggle', { active: isMobileMenuOpen }]"
        @click="toggleMobileMenu"
        aria-label="Toggle navigation"
      >
        <span></span>
        <span></span>
        <span></span>
      </button>

      <div :class="['nav-links-container', { 'mobile-menu-open': isMobileMenuOpen }]">
        <ul class="nav-links">
          <template v-if="isLoggedIn">
            <li>
              <RouterLink to="/tickets" class="nav-btn nav-btn-login" @click="handleMobileLinkClick"
                >My Tickets</RouterLink
              >
            </li>
            <li>
              <button @click="handleMobileLogoutClick" class="nav-btn nav-btn-start">Logout</button>
            </li>
          </template>
          <template v-else>
            <li>
              <RouterLink to="/login" class="nav-btn nav-btn-login" @click="handleMobileLinkClick"
                >Login</RouterLink
              >
            </li>
            <li>
              <RouterLink to="/login" class="nav-btn nav-btn-start" @click="handleMobileLinkClick"
                >Get Started</RouterLink
              >
            </li>
          </template>
        </ul>
      </div>
    </nav>
  </header>
</template>

<style scoped>
/* Scoped styles: Only affect this component */
</style>

// react-version/src/components/Header.jsx
// src/components/Header.jsx
// Combined React and useState import
import React, { useState } from "react";
// Keep Link and useNavigate
import { Link, useNavigate } from "react-router-dom";

function Header() {
  const navigate = useNavigate();
  // Check if logged in
  const isLoggedIn = !!localStorage.getItem("ticketapp_session");
  // State for mobile menu visibility
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  // Function to run when the logout button is clicked
  const handleLogout = () => {
    localStorage.removeItem("ticketapp_session"); // Delete the token
    navigate("/"); // Send user back to the landing page
  };

  // --- MOVED: Toggle function for mobile menu ---
  const toggleMobileMenu = () => {
    setIsMobileMenuOpen(!isMobileMenuOpen); // Flip the state
  };

  // --- NEW: Function to close menu when a mobile link is clicked ---
  const handleMobileLinkClick = () => {
    setIsMobileMenuOpen(false); // Close menu
  };

  // --- NEW: Function to handle logout AND close mobile menu ---
  const handleMobileLogoutClick = () => {
    handleLogout(); // Perform logout actions
    setIsMobileMenuOpen(false); // Close menu
  };

  return (
    <header className="main-header">
      <nav className="container">
        <Link to="/" className="logo">
          SOLPOINT
        </Link>

        {/* --- Hamburger Button (Connects to toggleMobileMenu) --- */}
        <button
          className={`mobile-nav-toggle ${isMobileMenuOpen ? "active" : ""}`} // Add 'active' class when open for potential 'X' icon styling
          onClick={toggleMobileMenu} // Use the correct toggle function
          aria-label="Toggle navigation"
        >
          <span></span>
          <span></span>
          <span></span>
        </button>

        {/* --- ADDED: Wrapper div for mobile overlay --- */}
        {/* Adds 'mobile-menu-open' class when state is true */}
        <div
          className={`nav-links-container ${
            isMobileMenuOpen ? "mobile-menu-open" : ""
          }`}
        >
          <ul className="nav-links">
            {/* Check if isLoggedIn is true or false */}
            {isLoggedIn ? (
              // If TRUE (user is logged in): Show these buttons
              <>
                <li>
                  {/* Add onClick to close menu */}
                  <Link
                    to="/tickets"
                    className="nav-btn nav-btn-login"
                    onClick={handleMobileLinkClick}
                  >
                    My Tickets
                  </Link>
                </li>
                <li>
                  {/* Use specific handler for mobile logout + close */}
                  <button
                    onClick={handleMobileLogoutClick}
                    className="nav-btn nav-btn-start"
                  >
                    Logout
                  </button>
                </li>
              </>
            ) : (
              // If FALSE (user is logged out): Show these buttons
              <>
                <li>
                  {/* Add onClick to close menu */}
                  <Link
                    to="/login"
                    className="nav-btn nav-btn-login"
                    onClick={handleMobileLinkClick}
                  >
                    Login
                  </Link>
                </li>
                <li>
                  {/* Add onClick to close menu */}
                  <Link
                    to="/login"
                    className="nav-btn nav-btn-start"
                    onClick={handleMobileLinkClick}
                  >
                    Get Started
                  </Link>
                </li>
              </>
            )}
          </ul>
        </div>
      </nav>
    </header>
  );
}

export default Header;
